name: Branch Push & PR CI/CD
on:
  push:
    branches:
      - '!master'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  score:
    name: "Score Package"
    uses: ./.github/workflows/score.yml
            
  analyse-test:
    name: "Analyse & Test"
    uses: ./.github/workflows/analyse-test.yml

  build-io:
    name: "Build IO Example Apps"
    needs: analyse-test
    uses: ./.github/workflows/build-io.yml

  build-web:
    name: "Build Web Example App"
    runs-on: ubuntu-latest
    needs: analyse-test
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Web Application
        run: flutter build web --web-renderer canvaskit
      - name: Archive Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: web-build
          path: example/build/web
          if-no-files-found: error